version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - npm ci --production # Only install production dependencies

  build:
    commands:
      - echo "Creating deployment package..."
      # Zip only what's needed for Lambda
      - zip -r function.zip index.mjs handlers/ utils/ services/ node_modules/ package.json package-lock.json
      - echo "Build completed successfully"

artifacts:
  files:
    - function.zip
  name: lambda-deployment-package
