version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - cd Yard-Be
      - npm ci --production

  build:
    commands:
      - echo "Creating deployment package..."
      - ls -la
      - zip -r ../function.zip index.mjs node_modules package.json handlers utils services

artifacts:
  files:
    - function.zip
