version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - npm ci --production

artifacts:
  files:
    - index.js
    - node_modules/**
    - package.json
    - package-lock.json
    - webhook/**
    - utils/**
    - services/**
