version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - npm ci --production   # Only install production dependencies

  build:
    commands:
      - echo "Creating deployment package..."
      # Zip contents of the project folder, keeping index.mjs at root
      - zip -r function.zip index.mjs node_modules package.json package-lock.json handlers utils services || true
      - echo "Build completed successfully"

artifacts:
  files:
    - function.zip
